### ISSUE TITLE
lodash security vulnerability

### ISSUE THREAD

**Issue by naugtur** [doowb/expand-hash#7]
(+) 1 vulnerability found

│            │ Prototype Pollution                                                │
│ Name       │ lodash                                                             │
│ CVSS       │ 2 (Low)                                                            │
│ Installed  │ 2.4.2                                                              │
│ Vulnerable │ <4.17.5                                                            │
│ Patched    │ >=4.17.5                                                           │
│ Path       │ gdocs@1.1.0 > expand-hash@0.2.2 > lodash@2.4.2                     │
│ More Info  │ https://nodesecurity.io/advisories/577                             │

**Comment by doowb** [comment]
@naugtur thanks. A PR would be great to remove `lodash` and use `Object.assign` instead. I try to get to it sometime if no one else does.

**Comment by naugtur** [comment]
@doowb can do (on Monday if I don't forget)
